/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-secondary-fixed": "#410002",
        "on-tertiary-fixed-variant": "#584400",
        "on-tertiary-container": "#4f3d00",
        "surface-dim": "#d9dadb",
        "on-primary-fixed-variant": "#00458f",
        "on-error-container": "#93000a",
        "outline-variant": "#c2c6d3",
        "background": "#f8f9fa",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1d",
        "error": "#ba1a1a",
        "inverse-primary": "#abc7ff",
        "surface-container-high": "#e7e8e9",
        "primary": "#00346f",
        "primary-container": "#004a99",
        "tertiary": "#745b00",
        "surface-container-low": "#f3f4f5",
        "secondary-fixed-dim": "#ffb4ab",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001b3f",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#9bbdff",
        "surface": "#f8f9fa",
        "secondary-container": "#e41f25",
        "inverse-surface": "#2e3132",
        "secondary-fixed": "#ffdad6",
        "inverse-on-surface": "#f0f1f2",
        "on-tertiary-fixed": "#241a00",
        "on-surface": "#191c1d",
        "on-error": "#ffffff",
        "primary-fixed": "#d7e2ff",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#255dad",
        "surface-container": "#edeeef",
        "tertiary-container": "#d0a600",
        "on-surface-variant": "#424751",
        "outline": "#737783",
        "secondary": "#bb0014",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#93000d",
        "tertiary-fixed-dim": "#f1c100",
        "on-secondary-container": "#fffbff",
        "surface-bright": "#f8f9fa",
        "primary-fixed-dim": "#abc7ff",
        "tertiary-fixed": "#ffe08b"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "md": "24px",
        "margin": "32px",
        "gutter": "24px",
        "xs": "4px",
        "lg": "48px",
        "sm": "12px",
        "base": "8px",
        "xl": "80px"
      },
      "fontFamily": {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Work Sans", "sans-serif"],
        "headline-xl": ["Work Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Work Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-xl": ["48px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
